
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flclient-deployment
spec:
  selector:
    matchLabels:
      app: fl-client-3
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fl-client-3
    spec:
      volumes:
        - name: shared-train-data # 학습데이터 저장용
          emptyDir: {}
        - name: shared-model # 모델 저장용
          emptyDir: {}
      containers:
          - name: fl-client
            image: docker.io/hoo0681/airflowkubepodimage:0.1
            resources:
              limits:
                memory: "5Gi"
                cpu: "1024m"
                nvidia.com/gpu: 1
            ports:
              - containerPort: 8002
            env:
            - name: REPO_URL
              value: "https://github.com/gachon-CCLab/Health_Flower_Client_3.git"
            - name: GIT_TAG
              value: "master"
            - name: GRPC_POLL_STRATEGY
              value: "epoll1"
            volumeMounts:
            - name: shared-train-data
              mountPath: /traindata #read
            - name: shared-model
              mountPath: /model #read/write

          - name: client-manager
            image: docker.io/hoo0681/gitclone_python:0.1
            resources:
              limits:
                memory: "2Gi"
                cpu: "500m"
            ports:
              - containerPort: 8080
            env:
            - name: REPO_URL
              value: "https://github.com/gachon-CCLab/Health_Client_Manager.git"
            - name: GIT_TAG
              value: "main"
            volumeMounts:
              - name: shared-model
                mountPath: /model #write
